### ISSUE TITLE
The Server is down

### ISSUE THREAD

**Issue by mendess** [ToyDragon/TTSDeckImporter#1]
...and I got the images from a deck that I made just before the server going down in [super low quality](http://prntscr.com/bhlazi)

I'm also going to take the opportunity to point out that the wierd token is a bit from mtgo and look [_wierd_ ](http://prntscr.com/bhlbvg)

**Comment by ToyDragon** [comment]
Thanks for the heads up. There are a lot of inconsistencies between my testing environment and the production environment that I'm trying to resolve, I think those changes broke something. I'll look at this today after work hours.

All of the tokens were selected manually and pretty haphazardly, feel free to email me with better token assets and I'll throw them in here.

**Comment by Mendess2526** [comment]
![image](https://cloud.githubusercontent.com/assets/19352680/16159105/b749d202-34b8-11e6-8744-bd8ab847af84.png)
the card images are still wierd! I set it to medium and high and it still gives the same result...

**Comment by ToyDragon** [comment]
Issue was due to the server running the old deck maker code and the new web server code.
