### ISSUE TITLE
Black (blank) Land cards using BFZ full arts

### ISSUE THREAD

**Issue by ghost** [ToyDragon/TTSDeckImporter#2]
Setting lands to be specific full art lands from the bfz set causes it to become black. 

Here is what I wrote in the deck list 

4   Forest [bfz]<274b>
4   Plains [bfz]<254b>
1   Swamp [bfz] <260b>
The cards were copy/pasted from a tappedout.net .txt document. I then added the [bfz]<Number> to the cards manually. This has worked fined in the past, but for some reason the card art is completely black when pulling out the .json into TTS. 
halp.

**Comment by ghost** [comment]
Changing the printing to the "a" printing works, but no "b" (full art) printing functions.

**Comment by ToyDragon** [comment]
Thanks for posting this, I don't test specific printings very often.
The issues was caused by bad file names.
